const fs = require('fs')
const fsp = fs.promises
const path = require('path')
const crypto = require('crypto')
const { atomicWriteJSON } = require('./atomic-write')
const { isValidId } = require('./store')

// Run ids are generated by us (never user-supplied on creation), but they
// ARE taken from the URL when looking a run up, so still validate strictly.
const RUN_ID_PATTERN = /^[0-9]{8}T[0-9]{6}-[a-z0-9]{6}$/

function newRunId () {
  const ts = new Date().toISOString().replace(/[-:]/g, '').replace(/\..+$/, '')
  return `${ts}-${crypto.randomBytes(3).toString('hex')}`
}

class RunHistoryStore {
  /** @param {string} dataDir the plugin's data directory (same one ChecklistStore uses) */
  constructor (dataDir) {
    this.runsDir = path.join(dataDir, 'runs')
  }

  _dirFor (listId) {
    if (!isValidId(listId)) throw new Error(`invalid list id: ${listId}`)
    return path.join(this.runsDir, listId)
  }

  _fileFor (listId, runId) {
    if (!RUN_ID_PATTERN.test(runId)) throw new Error(`invalid run id: ${runId}`)
    return path.join(this._dirFor(listId), `${runId}.json`)
  }

  /** Snapshot a completed list into its run history. Returns the stored run document. */
  async archiveRun (list) {
    const dir = this._dirFor(list.id)
    await fsp.mkdir(dir, { recursive: true })
    const run = {
      id: newRunId(),
      listId: list.id,
      listName: list.name,
      completedAt: new Date().toISOString(),
      items: list.items.map((item) => ({ ...item }))
    }
    await atomicWriteJSON(path.join(dir, `${run.id}.json`), run)
    return run
  }

  /**
   * Delete completed runs older than the list's configured retention
   * window. `retentionDays` of null/0/undefined means "keep forever" — a
   * no-op. Called both right after a new run is archived and whenever a
   * list's history is viewed, so retention takes effect without needing a
   * background scheduler.
   */
  async pruneExpiredRuns (listId, retentionDays) {
    if (!retentionDays) return
    const cutoff = Date.now() - retentionDays * 24 * 60 * 60 * 1000
    let entries
    try {
      entries = await fsp.readdir(this._dirFor(listId))
    } catch (err) {
      if (err.code === 'ENOENT') return
      throw err
    }
    for (const entry of entries) {
      if (!entry.endsWith('.json') || entry.endsWith('.tmp')) continue
      const runId = entry.slice(0, -'.json'.length)
      if (!RUN_ID_PATTERN.test(runId)) continue
      const filePath = path.join(this._dirFor(listId), entry)
      try {
        const run = JSON.parse(await fsp.readFile(filePath, 'utf8'))
        if (new Date(run.completedAt).getTime() < cutoff) {
          await fsp.unlink(filePath)
        }
      } catch (err) {
        // Skip unreadable/corrupt run files rather than failing the sweep.
      }
    }
  }

  /** Summaries of past completed runs for a list, most recent first. */
  async listRuns (listId) {
    let entries
    try {
      entries = await fsp.readdir(this._dirFor(listId))
    } catch (err) {
      if (err.code === 'ENOENT') return []
      throw err
    }
    const runs = []
    for (const entry of entries) {
      if (!entry.endsWith('.json') || entry.endsWith('.tmp')) continue
      const runId = entry.slice(0, -'.json'.length)
      if (!RUN_ID_PATTERN.test(runId)) continue
      try {
        const run = await this.getRun(listId, runId)
        if (run) runs.push(summarizeRun(run))
      } catch (err) {
        // Skip unreadable/corrupt run files rather than failing the whole listing.
      }
    }
    runs.sort((a, b) => (a.completedAt < b.completedAt ? 1 : -1))
    return runs
  }

  async getRun (listId, runId) {
    let raw
    try {
      raw = await fsp.readFile(this._fileFor(listId, runId), 'utf8')
    } catch (err) {
      if (err.code === 'ENOENT') return null
      throw err
    }
    return JSON.parse(raw)
  }
}

function summarizeRun (run) {
  const items = run.items.filter((i) => i.type === 'item')
  return {
    id: run.id,
    listId: run.listId,
    listName: run.listName,
    completedAt: run.completedAt,
    total: items.length,
    checked: items.filter((i) => i.checked).length
  }
}

module.exports = { RunHistoryStore }
